// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8zTHpjlcWnbbJpSa9GAn7FGyyn-7tGVU',
    appId: '1:1068709879852:web:2b446f45d81e04fae6f189',
    messagingSenderId: '1068709879852',
    projectId: 'finstagram-instagram-clone',
    authDomain: 'finstagram-instagram-clone.firebaseapp.com',
    storageBucket: 'finstagram-instagram-clone.appspot.com',
    measurementId: 'G-LQJRZHH6RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcEL8pAnc8XucGuULjTaFkh-tdnFauJns',
    appId: '1:1068709879852:android:4dec8aad435bd233e6f189',
    messagingSenderId: '1068709879852',
    projectId: 'finstagram-instagram-clone',
    storageBucket: 'finstagram-instagram-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIEzVJoqyGDVEY1XWqug8RrbwTq7n6WHY',
    appId: '1:1068709879852:ios:10a0b4f9e711a87ee6f189',
    messagingSenderId: '1068709879852',
    projectId: 'finstagram-instagram-clone',
    storageBucket: 'finstagram-instagram-clone.appspot.com',
    iosBundleId: 'com.example.finstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIEzVJoqyGDVEY1XWqug8RrbwTq7n6WHY',
    appId: '1:1068709879852:ios:10a0b4f9e711a87ee6f189',
    messagingSenderId: '1068709879852',
    projectId: 'finstagram-instagram-clone',
    storageBucket: 'finstagram-instagram-clone.appspot.com',
    iosBundleId: 'com.example.finstagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8zTHpjlcWnbbJpSa9GAn7FGyyn-7tGVU',
    appId: '1:1068709879852:web:7885f09e38c561aee6f189',
    messagingSenderId: '1068709879852',
    projectId: 'finstagram-instagram-clone',
    authDomain: 'finstagram-instagram-clone.firebaseapp.com',
    storageBucket: 'finstagram-instagram-clone.appspot.com',
    measurementId: 'G-YC3NL1K95H',
  );

}